# -*- coding: utf-8 -*-
"""clase18_05_26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Alejo9923/inteligencia_artificial/blob/main/clase18_05_26.ipynb

Inteligencia Artificial.
corpus (DATASET ventas.csv)
-Agentes
-RAG
-Mistral

Generar un BOT que pueda responder preguntas.
(ej, pasarle un parrafo y preguntar cual es la idea principal, el RAG tiene que pasarte eso)


-Crear una api key de mistral

!pip install pandas langchain langchain experimental tabulate langchain-ollama

normalizar el dataset en otro collab

# Clase 18/05/26

Inteligencia Artificial.
corpus (DATASET ventas.csv)
-Agentes
-RAG
-Mistral

Generar un BOT que pueda responder preguntas.
(ej, pasarle un parrafo y preguntar cual es la idea principal, el RAG tiene que pasarte eso)

1.   ¿Qué es un Corpus?


En el ámbito de la Inteligencia Artificial, el Procesamiento del Lenguaje Natural (PLN) y la lingüística computacional, un corpus (en plural, corpora) es un conjunto amplio, estructurado y digitalizado de textos o datos lingüísticos que se recopila siguiendo criterios específicos para ser utilizado como material de análisis, entrenamiento o consulta.

No es simplemente "un montón de datos tirados en un archivo". Para que un conjunto de textos se considere un corpus, debe cumplir con ciertas propiedades:


*   Representatividad:

Debe reflejar fielmente el lenguaje del dominio que busca estudiar. En tu caso, un corpus de ventas debe contener el vocabulario técnico, las interacciones, las quejas, las descripciones de productos y las transacciones reales de ese entorno.


*   Estructura y Metadatos:

Los datos suelen estar anotados o indexados. En un archivo CSV de ventas, cada columna (fecha, cliente, descripción, motivo de la llamada, etc.) actúa como una etiqueta estructural que le da contexto semántico al texto.


*   Propósito:
Se diseña con un fin estadístico o de modelado. Los modelos de IA no "entienden" de forma mágica; necesitan procesar miles de ejemplos de un corpus para identificar patrones probabilísticos (por ejemplo, qué palabras suelen aparecer juntas cuando un cliente está insatisfecho).



2.   ¿Qué son los Agentes en IA?

Un Agente Inteligente es una entidad de software capaz de percibir su entorno, procesar esa información y tomar decisiones de manera autónoma para ejecutar acciones con el objetivo de alcanzar una meta específica.

Si un modelo de lenguaje tradicional (LLM) es como un cerebro en una cubeta que solo responde cuando le hablas, un agente es ese mismo cerebro con manos, ojos y capacidad de planificar.

Componentes de la Arquitectura de un Agente:
*   Perfil/Rol (Persona): Define el objetivo, los límites y el comportamiento del agente. Por ejemplo: "Eres un auditor analítico del departamento de ventas". Esto condiciona cómo interpreta el entorno.
*   Memoria:
--   Corto Plazo: El contexto de la conversación actual (el hilo del chat).
--   Largo Plazo: Capacidad de recordar interacciones pasadas a través de bases de datos externas.
*   Planificación (Planning): El agente desglosa un problema complejo en subtareas. Utiliza frameworks como ReAct (Reasoning and Acting), donde el agente sigue un bucle de: Pensamiento (analiza la situación) $\rightarrow$ Acción (ejecuta una herramienta) $\rightarrow$ Observación (mide el resultado) y repite hasta resolver el problema
*   Herramientas (Tools/Skills): Son las interfaces que le permiten al agente salir de su "caja". Pueden ser scripts de Python, calculadoras, APIs de clima o, crucialmente, un sistema RAG. El agente no tiene el conocimiento de las ventas en su memoria interna, pero sabe que tiene una herramienta para ir a buscarlo.

3.  ¿Qué es RAG (Retrieval-Augmented Generation)?

La Generación Aumentada por Recuperación es un patrón de arquitectura diseñado para resolver los dos grandes problemas de los LLMs: la falta de conocimiento de datos privados y las alucinaciones (cuando el modelo inventa datos con total seguridad).

En lugar de reentrenar a un modelo multimillonario con tus datos de ventas cada vez que estos cambian, RAG actúa como un examen a libro abierto. El proceso se divide en dos fases matemáticas y lógicas profundas:

Fase 1: Indexación (Preparación del Corpus)
1. Segmentación (Chunking): El corpus (tu ventas.csv) se divide en fragmentos pequeños y lógicos.

2. Generación de Embeddings: Cada fragmento de texto pasa por un modelo matemático que lo convierte en un vector (una lista de números, por ejemplo, en un espacio de 768 dimensiones). Este vector representa el significado semántico del texto. Palabras como "pérdida" y "déficit" quedarán geométricamente muy cerca en este espacio vectorial, aunque se escriban diferente.

3. Base de Datos Vectorial: Los vectores se almacenan en un índice especializado (como Chroma o Pinecone).

Fase 2:
* El usuario hace una pregunta: "¿Cuál fue el problema principal con las laptops?".

* La pregunta se convierte en un vector usando el mismo modelo de embeddings.

* Se realiza una búsqueda de similitud de coseno en la base de datos vectorial para encontrar el fragmento del corpus de ventas numéricamente más cercano a la duda del usuario.

* Inyección de Contexto: El sistema toma ese fragmento recuperado y lo empaqueta junto a la pregunta original en un "prompt" optimizado.

* El LLM recibe el paquete y, en lugar de adivinar, simplemente redacta la respuesta basándose estrictamente en el texto que se le acaba de proveer.





4. ¿Qué es Mistral?
Mistral (específicamente desarrollado por la empresa francesa Mistral AI) es una familia de Modelos de Lenguaje Grande (LLMs) de código abierto y comerciales que irrumpieron fuertemente en la comunidad debido a su eficiencia matemática superior frente a modelos gigantescos como GPT-4.

Para entender a Mistral, hay que entender dos innovaciones técnicas que implementa en su arquitectura de red neuronal (específicamente en modelos como Mistral 7B o Mixtral):
*  Atención de Consulta Agrupada (Grouped-Query Attention - GQA): En los Transformers tradicionales, calcular la relación de cada palabra con todas las demás consume mucha memoria RAM y tiempo de procesamiento. GQA agrupa las claves de atención, lo que permite que el modelo sea drásticamente más rápido al procesar textos largos sin perder precisión.
* Atención de Ventana Deslizante (Sliding Window Attention - SWA): Mistral no analiza todo el documento eterno de golpe; utiliza una "ventana" que se desliza sobre el texto, prestando atención principalmente a los tokens (palabras o fragmentos) relativamente cercanos. Esto reduce el costo computacional de un orden cuadrático a uno lineal.
* Arquitectura de Mezcla de Expertos (MoE - Mixture of Experts): En sus versiones más avanzadas (como Mixtral), el modelo no activa todas sus neuronas para responderte. Está compuesto por varios submodelos ("expertos"). Si le preguntas sobre matemáticas, un "enrutador" interno dirige la pregunta solo a los expertos en matemáticas, dejando el resto apagado. Esto da el poder de un modelo gigante con la velocidad de uno pequeño.


¿Cómo se conecta todo en tu proyecto?
Tu Corpus (ventas.csv) contiene la verdad de los datos. El sistema RAG fragmenta y vectoriza ese corpus para poder extraer la información exacta en milisegundos. El Agente recibe la orden del usuario, razona si necesita el RAG o no, extrae la información relevante y se la presenta a Mistral. Finalmente, Mistral lee los datos crudos del RAG y redacta para ti la "idea principal" con una redacción humana perfecta.

# Normalizacion del DATASET
"""

# 1. Instalar librerías de soporte (si es necesario)
!pip install -q pandas tabulate

import pandas as pd
from google.colab import files

# 2. Subir el archivo de Kaggle directamente desde tu computadora
print("Por favor, selecciona y sube tu archivo CSV de Kaggle:")
uploaded = files.upload()

# 3. Leer el archivo con Pandas
# Nota: Los datasets de Kaggle a veces usan codificaciones como 'latin-1' o 'ISO-8859-1'
nombre_archivo = list(uploaded.keys())[0]
df = pd.read_csv(nombre_archivo, encoding='latin-1')

# Mostrar las primeras 3 filas para verificar que cargó bien
df.head(3)

# Ver información general de las columnas, tipos de datos y nulos
print("--- Estructura del Dataset ---")
df.info()

print("\n--- Columnas Disponibles ---")
print(df.columns.tolist())

# 1. Calcular el total de NaN por columna
conteo_nan = df.isna().sum()

# 2. Filtrar solo las columnas que tienen al menos un NaN para no saturar la vista
columnas_con_nan = conteo_nan[conteo_nan > 0]

print("--- Conteo de valores faltantes (NaN) por columna ---")
if not columnas_con_nan.empty:
    # Creamos un DataFrame secundario para mostrarlo lindo con tabulate
    df_nan = pd.DataFrame({
        'Columna': columnas_con_nan.index,
        'Cantidad de NaNs': columnas_con_nan.values,
        'Porcentaje (%)': (columnas_con_nan.values / len(df) * 100).round(2)
    })
    from tabulate import tabulate
    print(tabulate(df_nan, headers='keys', tablefmt='psql', showindex=False))
else:
    print("¡Buenas noticias! No se encontraron valores NaN en ninguna columna.")

import re
import unicodedata

# Función auxiliar para limpiar texto a fondo (eliminar acentos y caracteres raros)
def limpiar_texto_avanzado(texto):
    if pd.isna(texto):
        return "unknown"

    # 1. Convertir a string y a minúsculas
    texto = str(texto).lower().strip()

    # 2. Eliminar acentos (Ej: 'camión' -> 'camion')
    texto = unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('utf-8')

    # 3. Reemplazar espacios y guiones intermedios por un único guión bajo
    texto = re.sub(r'[\s\-]+', '_', texto)

    # 4. Eliminar cualquier carácter que no sea una letra, número o guión bajo
    texto = re.sub(r'[^a-z0-9_]', '', texto)

    return texto

# --- APLICAR LA NORMALIZACIÓN ---

# 1. Normalizar los NOMBRES DE LAS COLUMNAS (Ej: "Product Line" -> "product_line")
df.columns = [limpiar_texto_avanzado(col) for col in df.columns]

# 2. Identificar columnas categóricas o de texto para normalizar su CONTENIDO
# (Ej: En Kaggle "Classic Cars" -> "classic_cars", "In Process" -> "in_process")
columnas_texto = df.select_dtypes(include=['object']).columns

for col in columnas_texto:
    df[col] = df[col].apply(limpiar_texto_avanzado)

# 3. Manejar los valores nulos remanentes en columnas críticas ahora normalizadas
columnas_con_nulos = ['territory', 'state']
for col in columnas_con_nulos:
    if col in df.columns:
        df[col] = df[col].replace('unknown', 'unknown').fillna('unknown')

# 4. Mostrar el resultado ultra-limpio
from tabulate import tabulate
print("--- Dataset con Normalización Avanzada ---")
print(tabulate(df.head(5), headers='keys', tablefmt='psql'))

# Guardar el dataset normalizado
archivo_salida = "ventas_normalizado.csv"
df.to_csv(archivo_salida, index=False)

# Descargarlo automáticamente a tu computadora
files.download(archivo_salida)
print(f"¡Listo! El archivo '{archivo_salida}' se ha normalizado y descargado.")

"""# Configuracion de Mistral y sistema RAG"""

##Instalación Limpia de Librerías de IA
# Instalación de todas las librerías necesarias para el BOT, RAG y la API de Mistral
# LangChain dividió su código en varios paquetes a partir de la v0.1.
# langchain          → núcleo: cadenas, prompts, RetrievalQA
# langchain-community → integraciones externas: ChromaDB, HuggingFace, DataFrameLoader
# langchain-mistralai → integración específica con la API de Mistral
# chromadb            → base de datos vectorial que usa Chroma internamente
# sentence-transformers → modelo de embeddings all-MiniLM-L6-v2
# Instalamos todo junto para evitar conflictos de versión.
!pip install -q \
    langchain \
    langchain-community \
    langchain-mistralai \
    chromadb \
    sentence-transformers \
    pandas \
    tabulate
!pip install -q langchain-core

import os
import pandas as pd
from google.colab import files
from google.colab import userdata

# 1. Subir el corpus limpio que generamos en el paso anterior
print("Por favor, sube tu archivo 'ventas_normalizado.csv':")
uploaded = files.upload()
nombre_csv = list(uploaded.keys())[0]
df_limpio = pd.read_csv(nombre_csv, encoding='latin-1')

# 2. Configurar la API Key de Mistral de forma segura
try:
    # Intenta buscar la variable en tus "Secrets" (icono de la llave a la izquierda)
    os.environ["MISTRAL_API_KEY"] = userdata.get('MISTRAL_API_KEY')
    print("¡API Key cargada exitosamente desde los Secrets de Colab!")
except Exception:
    # Si no la encuentra o no está configurada, te la pide manualmente en pantalla
    print("No se encontró la clave en 'Secrets'.")
    os.environ["MISTRAL_API_KEY"] = input("Introduce tu Mistral API Key manualmente: ")

print("\n¡Dataset cargado correctamente y entorno listo!")

# ============================================================
# BLOQUE RAG — Generación de vectores (versión mejorada)
# Reemplazá el bloque anterior de "Estructuración del RAG"
# con este. La diferencia: el resumen_fila se construye de
# forma dinámica leyendo las columnas reales del CSV, en lugar
# de tener los nombres hardcodeados. Así funciona con cualquier
# dataset sin necesidad de editar el código.
# ============================================================

from langchain_community.document_loaders import DataFrameLoader
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# 1. Construir el resumen de cada fila de forma dinámica.
#    En lugar de hardcodear columnas, tomamos todas las que
#    existen en el CSV. Cada fila queda como un párrafo del
#    estilo "columna: valor. columna: valor." que el modelo
#    puede leer y entender como lenguaje natural.
def fila_a_texto(row):
    partes = []
    for col in row.index:
        valor = row[col]
        if pd.notna(valor):
            partes.append(f"{col}: {valor}")
    return ". ".join(partes) + "."

df_limpio['resumen_fila'] = df_limpio.apply(fila_a_texto, axis=1)

# Verificar cómo quedó un ejemplo para asegurarnos que el texto
# tiene sentido antes de vectorizar todo el dataset.
print("Ejemplo de fila convertida a texto:")
print(df_limpio['resumen_fila'].iloc[0])

# 2. DataFrameLoader convierte cada fila del CSV en un
#    "Document" de LangChain. Le indicamos qué columna usar
#    como contenido principal (el resumen que acabamos de crear).
loader = DataFrameLoader(df_limpio, page_content_column='resumen_fila')
documentos = loader.load()
print(f"\nTotal de documentos indexados: {len(documentos)}")

# 3. Modelo de embeddings: convierte texto → vector numérico.
#    Usamos "all-MiniLM-L6-v2" porque es gratuito, liviano y
#    corre directo en la RAM de Colab (no necesita API key).
#    Cada fragmento de texto queda representado como un punto
#    en un espacio de 384 dimensiones.
print("\nTransformando el corpus a vectores semánticos...")
embeddings_local = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# 4. Chroma es nuestra base de datos vectorial (vive en RAM).
#    El retriever es el "buscador": dada una pregunta del usuario,
#    la convierte en vector y devuelve los k=5 documentos más
#    similares del corpus. k=5 da más contexto que k=3.
vector_db = Chroma.from_documents(documentos, embeddings_local)
retriever = vector_db.as_retriever(search_kwargs={"k": 5})

print("¡Sistema RAG indexado y listo!")

# ============================================================
# BLOQUE 4 — Inicializar Mistral como LLM
# Acá conectamos con la API de Mistral AI para usar su modelo
# de lenguaje como el "cerebro" del bot. Mistral recibe el
# contexto recuperado por el RAG y redacta la respuesta final.
# Usamos "mistral-small-latest" porque es el modelo más rápido
# y económico de Mistral, ideal para preguntas analíticas.
# ============================================================

from langchain_mistralai import ChatMistralAI

# ChatMistralAI se conecta a la API usando la variable de entorno
# MISTRAL_API_KEY que ya configuramos en el bloque anterior.
# temperature=0.2 significa respuestas más deterministas y
# precisas (0 = siempre igual, 1 = más creativo). Para análisis
# de datos conviene mantenerlo bajo.
llm = ChatMistralAI(
    model="mistral-small-latest",
    temperature=0.2
)

# Verificación rápida: le hacemos una pregunta simple para
# confirmar que la API key funciona y el modelo responde.
respuesta_test = llm.invoke("Respondé en una línea: ¿estás listo para analizar datos?")
print("Test de conexión con Mistral:")
print(respuesta_test.content)

# ============================================================
# BLOQUE 5 — Construir la cadena RAG (versión moderna)
# LangChain eliminó RetrievalQA en versiones recientes y ahora
# recomienda construir la cadena manualmente usando LCEL
# (LangChain Expression Language), que encadena pasos con el
# operador | (pipe). El flujo es el mismo de antes:
#   pregunta → retriever → prompt con contexto → Mistral → respuesta
# ============================================================

from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# El prompt es el mismo que antes: define el rol del bot y
# dónde se inyectan el contexto recuperado y la pregunta.
prompt_template = PromptTemplate.from_template("""Eres un analista experto en ventas. Tienes acceso a un corpus
de datos de ventas reales. Responde ÚNICAMENTE basándote en el contexto
proporcionado. Si la información no está en el contexto, di exactamente:
"No encontré esa información en los datos disponibles."

Responde siempre en español, de forma clara y concisa.

Contexto del corpus de ventas:
{context}

Pregunta del usuario:
{question}

Respuesta del analista:""")

# Función auxiliar que convierte la lista de documentos
# recuperados por el retriever en un solo bloque de texto
# para pasárselo al prompt como {context}.
def formatear_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

# Cadena LCEL: cada | conecta un paso con el siguiente.
#   RunnablePassthrough() → deja pasar la pregunta sin cambios
#   retriever | formatear_docs → busca documentos y los une en texto
#   prompt_template → arma el prompt completo con contexto + pregunta
#   llm → Mistral genera la respuesta
#   StrOutputParser() → extrae solo el texto de la respuesta
cadena_rag = (
    {
        "context": retriever | formatear_docs,
        "question": RunnablePassthrough()
    }
    | prompt_template
    | llm
    | StrOutputParser()
)

print("✓ Cadena RAG construida correctamente.")
print("✓ Flujo: Pregunta → RAG (corpus) → Mistral → Respuesta")

# ============================================================
# BLOQUE 6 — Bot interactivo de preguntas y respuestas
# Este bloque arranca el loop de conversación. El bot queda
# esperando tus preguntas hasta que escribas "salir".
# En cada iteración el sistema completo hace:
#   1. Leer tu pregunta
#   2. Vectorizarla con el mismo modelo de embeddings
#   3. Buscar los 5 registros más similares en ChromaDB
#   4. Armar el prompt con contexto + pregunta
#   5. Enviar todo a Mistral y mostrar la respuesta
#
# Preguntas de ejemplo para probar:
#   - "¿Cuál es la línea de producto más vendida?"
#   - "¿Qué países generan más ventas?"
#   - "¿Cuántos pedidos tienen estado shipped?"
#   - "¿Cuál es el precio promedio por unidad?"
# ============================================================

print("=" * 55)
print("  BOT ANALISTA DE VENTAS — powered by Mistral + RAG")
print("  Escribí 'salir' para terminar la sesión.")
print("=" * 55)

while True:
    # Leer la pregunta del usuario desde la consola de Colab
    pregunta = input("\n¿Qué querés saber sobre las ventas?\n> ").strip()

    if not pregunta:
        continue

    if pregunta.lower() == "salir":
        print("\nSesión finalizada. ¡Hasta la próxima!")
        break

    try:
         respuesta = cadena_rag.invoke(pregunta)
         print("\n── Respuesta del analista ──────────────────────────")
         print(respuesta)

    except Exception as e:
        print(f"\nError al procesar la pregunta: {e}")
        print("Verificá que la API key de Mistral sea válida y que el RAG esté inicializado.")