# -*- coding: utf-8 -*-
"""clase_08_06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idKOJQ5QmRb6obMmIztxISlcwwhiL081
"""

# ============================================================
# BLOQUE 0 — INSTALACIÓN DE LIBRERÍAS
# ============================================================
# Instalar todas las dependencias del proyecto.
# Reiniciar el runtime si es necesario tras la instalación.
#
# kaggle       — cliente oficial de Kaggle para descargar datasets
# pandas       — manipulación y análisis de datos en DataFrames
# numpy        — operaciones numéricas y matriciales
# scikit-learn — preprocesamiento, modelos ML y métricas
# transformers — modelos de lenguaje preentrenados (HuggingFace)
# torch        — backend de PyTorch para ejecutar transformers
# accelerate   — optimiza la ejecución de modelos HuggingFace

!pip install kaggle pandas numpy scikit-learn transformers==4.41.0 torch accelerate --quiet

# ============================================================
# BLOQUE 1 — CARGA DEL DATASET DESDE ARCHIVO LOCAL
# ============================================================
# Subir el archivo manualmente desde la PC usando el selector
# de archivos de Google Colab.

import pandas as pd
from google.colab import files

print("Subir el archivo Titanic-Dataset.csv cuando aparezca el selector...")
uploaded = files.upload()

# Leer el CSV en un DataFrame
df_raw = pd.read_csv("Titanic-Dataset.csv")

print(f"Dataset cargado: {df_raw.shape[0]} filas x {df_raw.shape[1]} columnas")
print(df_raw.head())

# ============================================================
# BLOQUE 2 — EXPLORACIÓN INICIAL DEL DATASET
# ============================================================
# Analizar la estructura del dataset antes de pasarlo al
# Agente 1 para entender qué trabajo de limpieza es necesario.

import pandas as pd
import numpy as np

print("=" * 60)
print("EXPLORACIÓN INICIAL DEL DATASET RAW")
print("=" * 60)

# shape devuelve una tupla (filas, columnas)
print(f"\nDimensiones: {df_raw.shape[0]} filas x {df_raw.shape[1]} columnas")

# dtypes.value_counts() cuenta columnas por tipo de dato
print(f"\nTipos de datos:")
for tipo, cantidad in df_raw.dtypes.value_counts().items():
    print(f"   {tipo}: {cantidad} columnas")

# isnull().sum() cuenta valores nulos por columna
nulos = df_raw.isnull().sum()
nulos_cols = nulos[nulos > 0]
print(f"\nColumnas con valores nulos ({len(nulos_cols)}):")
for col, cantidad in nulos_cols.items():
    pct = cantidad / len(df_raw) * 100
    print(f"   {col:<15} {cantidad:>4} nulos  ({pct:.1f}%)")

# Separar columnas por tipo de dato
cols_numericas   = df_raw.select_dtypes(include=[np.number]).columns.tolist()
cols_categoricas = df_raw.select_dtypes(include=["object"]).columns.tolist()

print(f"\nColumnas numericas  : {cols_numericas}")
print(f"Columnas categoricas: {cols_categoricas}")

# describe() calcula estadisticas descriptivas de columnas numericas
print(f"\nEstadisticas descriptivas:")
print(df_raw.describe().T.round(2).to_string())

# Variable objetivo
print(f"\nVariable objetivo: 'Survived'")
print(df_raw["Survived"].value_counts())
print(f"   Tasa de supervivencia: {df_raw['Survived'].mean()*100:.1f}%")

# ============================================================
# BLOQUE 3 — AGENTE 1: NORMALIZADOR
# ============================================================
# Recibir el dataset crudo y devolver un dataset limpio,
# imputado, escalado y codificado.
#
# Pipeline interno:
#   1. Separar features (X) del target (y)
#   2. Descartar columnas sin valor predictivo
#   3. Identificar columnas numericas y categoricas
#   4. Imputar valores nulos
#   5. Escalar columnas numericas
#   6. Codificar columnas categoricas (One-Hot Encoding)

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
# SimpleImputer: rellenar NaN con una estrategia definida
# strategy="median"        — para numericas, robusto a outliers
# strategy="most_frequent" — para categoricas, usa el valor mas comun

from sklearn.preprocessing import StandardScaler, OneHotEncoder
# StandardScaler: transforma cada feature a media=0, std=1
# OneHotEncoder: convierte categorias en columnas binarias

from sklearn.pipeline import Pipeline
# Pipeline: encadenar transformadores en orden garantizado
# Evita data leakage: los parametros se aprenden solo en train

from sklearn.compose import ColumnTransformer
# ColumnTransformer: aplicar pipelines distintos por tipo de columna


def agente_normalizador(df: pd.DataFrame, target_col: str = "Survived") -> dict:
    """
    Agente 1 — Normalizador.

    Recibe el DataFrame crudo y devuelve un diccionario con:
      - X_procesado  : array limpio, escalado y codificado
      - y            : Series con el target
      - preprocessor : ColumnTransformer ajustado
      - feature_names: nombres de columnas del array procesado
      - reporte      : dict con estadisticas del proceso
    """

    print("=" * 60)
    print("AGENTE 1 — NORMALIZADOR")
    print("=" * 60)

    # Separar target del resto de features
    y = df[target_col]
    X = df.drop(columns=[target_col])

    print(f"\n[PASO 1] Target separado: '{target_col}'")

    # Descartar columnas sin valor predictivo:
    # PassengerId — identificador sin relacion con supervivencia
    # Name        — texto libre, demasiado unico para ser util
    # Ticket      — codigo alfanumerico sin patron claro
    # Cabin       — 77% de valores nulos
    cols_descartar = ["PassengerId", "Name", "Ticket", "Cabin"]
    X = X.drop(columns=cols_descartar, errors="ignore")

    print(f"[PASO 2] Columnas descartadas: {cols_descartar}")
    print(f"         Features restantes: {X.shape[1]} columnas — {list(X.columns)}")

    # Identificar columnas por tipo de dato
    cols_num = X.select_dtypes(include=[np.number]).columns.tolist()
    cols_cat = X.select_dtypes(include=["object"]).columns.tolist()

    print(f"\n[PASO 3] Columnas numericas  : {cols_num}")
    print(f"         Columnas categoricas: {cols_cat}")

    # Registrar nulos antes de imputacion
    nulos_num = int(X[cols_num].isnull().sum().sum())
    nulos_cat = int(X[cols_cat].isnull().sum().sum())

    print(f"\n[PASO 4] Nulos detectados:")
    print(f"         Numericas  : {nulos_num}  (Age)")
    print(f"         Categoricas: {nulos_cat}  (Embarked)")

    # Pipeline para columnas numericas:
    # imputar con mediana (robusta a outliers) y luego escalar
    pipeline_numerico = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler",  StandardScaler())
    ])

    # Pipeline para columnas categoricas:
    # imputar con el valor mas frecuente y codificar con OHE
    pipeline_categorico = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(
            handle_unknown="ignore",  # categorias nuevas en test generan columna de ceros
            sparse_output=False       # devolver array denso en lugar de matriz sparse
        ))
    ])

    # Combinar ambos pipelines aplicando cada uno a su subset de columnas
    preprocessor = ColumnTransformer(transformers=[
        ("num", pipeline_numerico,   cols_num),
        ("cat", pipeline_categorico, cols_cat)
    ], remainder="drop")

    # fit_transform aprende parametros y transforma en un solo paso
    print(f"\n[PASO 8] Ajustando y transformando...")
    X_procesado = preprocessor.fit_transform(X)

    # Recuperar nombres de columnas del output
    feature_names = preprocessor.get_feature_names_out()

    print(f"\n[PASO 9] Resultado:")
    print(f"         Shape final          : {X_procesado.shape}")
    print(f"         Features numericas   : {len([n for n in feature_names if 'num__' in n])}")
    print(f"         Features OHE         : {len([n for n in feature_names if 'cat__' in n])}")
    print(f"         Nulos despues        : {np.isnan(X_procesado).sum()}")
    print(f"         Columnas generadas   : {list(feature_names)}")

    reporte = {
        "filas"              : int(X_procesado.shape[0]),
        "columnas_input"     : int(df.shape[1]),
        "columnas_output"    : int(X_procesado.shape[1]),
        "cols_descartadas"   : cols_descartar,
        "cols_numericas"     : cols_num,
        "cols_categoricas"   : cols_cat,
        "nulos_num_antes"    : nulos_num,
        "nulos_cat_antes"    : nulos_cat,
        "nulos_despues"      : int(np.isnan(X_procesado).sum()),
        "tasa_supervivencia" : round(float(y.mean()) * 100, 1),
        "feature_names"      : list(feature_names),
    }

    print("\nAgente 1 completado. Dataset limpio listo para el Agente 2.")

    return {
        "X_procesado"  : X_procesado,
        "y"            : y,
        "preprocessor" : preprocessor,
        "feature_names": feature_names,
        "reporte"      : reporte
    }


resultado_agente1 = agente_normalizador(df_raw, target_col="Survived")

# ============================================================
# BLOQUE 4 — AGENTE 2: ENTRENADOR
# ============================================================
# Recibir el dataset limpio del Agente 1, aplicar validacion
# cruzada, entrenar multiples modelos de clasificacion,
# seleccionar el mejor y retornar metricas.
#
# El target 'Survived' es binario (0 o 1), por lo que el
# problema es de clasificacion.
#
# Librerias utilizadas:
#   train_test_split          — dividir datos en train y test
#   cross_val_score           — validacion cruzada k-fold
#   LogisticRegression        — modelo lineal para clasificacion binaria
#   RandomForestClassifier    — ensamble de arboles de decision
#   GradientBoostingClassifier— boosting secuencial de arboles
#   accuracy_score            — proporcion de predicciones correctas
#   roc_auc_score             — area bajo la curva ROC
#   confusion_matrix          — matriz de verdaderos/falsos positivos y negativos

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    roc_auc_score,
    confusion_matrix
)


def agente_entrenador(resultado_agente1: dict, random_state: int = 42) -> dict:
    """
    Agente 2 — Entrenador.

    Recibe el diccionario de salida del Agente 1 y devuelve:
      - mejor_modelo  : modelo con mejor AUC en test
      - nombre_mejor  : nombre del mejor modelo
      - metricas      : dict con metricas de todos los modelos
      - y_test        : valores reales del conjunto de prueba
      - y_pred_mejor  : predicciones del mejor modelo en test
      - reporte       : dict con resumen para el Agente 3

    Parametros:
      resultado_agente1 — dict devuelto por agente_normalizador()
      random_state      — semilla para reproducibilidad
    """

    print("=" * 60)
    print("AGENTE 2 — ENTRENADOR")
    print("=" * 60)

    X = resultado_agente1["X_procesado"]
    y = resultado_agente1["y"].values  # convertir Serie a array para sklearn

    # Division train/test estratificada para mantener la proporcion
    # de clases (38% survived) en ambos conjuntos
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=random_state,
        stratify=y
    )

    print(f"\n[PASO 1] Division del dataset (stratified):")
    print(f"         Train: {X_train.shape[0]} muestras")
    print(f"         Test : {X_test.shape[0]} muestras")
    print(f"         Proporcion survived en train: {y_train.mean()*100:.1f}%")
    print(f"         Proporcion survived en test : {y_test.mean()*100:.1f}%")

    modelos = {
        "Logistic Regression": LogisticRegression(
            max_iter=1000,       # iteraciones suficientes para garantizar convergencia
            random_state=random_state,
            C=1.0                # regularizacion L2 por defecto
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=200,    # numero de arboles del ensamble
            max_depth=10,        # profundidad maxima para limitar overfitting
            min_samples_split=5, # minimo de muestras para dividir un nodo
            random_state=random_state,
            n_jobs=-1
        ),
        "Gradient Boosting": GradientBoostingClassifier(
            n_estimators=200,    # numero de arboles secuenciales
            learning_rate=0.05,  # paso de actualizacion en cada iteracion
            max_depth=4,         # arboles poco profundos, ideal para boosting
            subsample=0.8,       # fraccion de muestras por arbol (stochastic boosting)
            random_state=random_state
        )
    }

    print(f"\n[PASO 2] Modelos a evaluar: {list(modelos.keys())}")

    resultados = {}

    for nombre, modelo in modelos.items():
        print(f"\n[ENTRENANDO] {nombre}...")

        # Validacion cruzada con 5 folds usando AUC como metrica
        # AUC es mas informativa que accuracy para clases desbalanceadas
        cv_scores = cross_val_score(
            modelo, X_train, y_train,
            cv=5,
            scoring="roc_auc",
            n_jobs=-1
        )

        # Entrenar el modelo final sobre todo X_train
        modelo.fit(X_train, y_train)

        # predict() devuelve la clase predicha (0 o 1)
        y_pred = modelo.predict(X_test)

        # predict_proba()[:,1] devuelve la probabilidad de clase positiva
        # necesaria para calcular AUC
        y_prob = modelo.predict_proba(X_test)[:, 1]

        accuracy = accuracy_score(y_test, y_pred)
        auc      = roc_auc_score(y_test, y_prob)

        cm = confusion_matrix(y_test, y_pred)
        tn, fp, fn, tp = cm.ravel()

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

        resultados[nombre] = {
            "modelo"      : modelo,
            "y_pred"      : y_pred,
            "y_prob"      : y_prob,
            "accuracy"    : accuracy,
            "auc"         : auc,
            "precision"   : precision,
            "recall"      : recall,
            "f1"          : f1,
            "cv_auc_mean" : cv_scores.mean(),
            "cv_auc_std"  : cv_scores.std(),
            "confusion"   : {"tn": int(tn), "fp": int(fp),
                             "fn": int(fn), "tp": int(tp)},
        }

        print(f"         CV AUC  : {cv_scores.mean():.4f} +/- {cv_scores.std():.4f}")
        print(f"         Test AUC: {auc:.4f}")
        print(f"         Accuracy: {accuracy:.4f}")
        print(f"         F1 Score: {f1:.4f}")
        print(f"         Precision: {precision:.4f} | Recall: {recall:.4f}")
        print(f"         Confusion: TN={tn} FP={fp} FN={fn} TP={tp}")

    # Seleccionar el mejor modelo por AUC:
    # metrica independiente del umbral de decision y robusta
    # ante clases desbalanceadas
    nombre_mejor = max(resultados, key=lambda k: resultados[k]["auc"])
    mejor        = resultados[nombre_mejor]

    print(f"\n[PASO 4] Mejor modelo: {nombre_mejor}")
    print(f"         AUC      = {mejor['auc']:.4f}")
    print(f"         Accuracy = {mejor['accuracy']:.4f}")
    print(f"         F1       = {mejor['f1']:.4f}")

    print(f"\n[PASO 5] Tabla comparativa:")
    print(f"{'Modelo':<25} {'AUC':>8} {'Accuracy':>10} {'F1':>8} {'CV AUC':>10}")
    print("-" * 65)
    for n, r in resultados.items():
        marca = " <- MEJOR" if n == nombre_mejor else ""
        print(f"{n:<25} {r['auc']:>8.4f} {r['accuracy']:>10.4f} "
              f"{r['f1']:>8.4f} {r['cv_auc_mean']:>10.4f}{marca}")

    reporte = {
        "mejor_modelo_nombre" : nombre_mejor,
        "auc"                 : round(mejor["auc"], 4),
        "accuracy"            : round(mejor["accuracy"], 4),
        "f1"                  : round(mejor["f1"], 4),
        "precision"           : round(mejor["precision"], 4),
        "recall"              : round(mejor["recall"], 4),
        "cv_auc_mean"         : round(mejor["cv_auc_mean"], 4),
        "cv_auc_std"          : round(mejor["cv_auc_std"], 4),
        "confusion"           : mejor["confusion"],
        "n_train"             : int(X_train.shape[0]),
        "n_test"              : int(X_test.shape[0]),
        "n_features"          : int(X_train.shape[1]),
        "tasa_supervivencia"  : round(float(y.mean()) * 100, 1),
        "todos_resultados"    : {
            k: {
                "auc"         : round(v["auc"], 4),
                "accuracy"    : round(v["accuracy"], 4),
                "f1"          : round(v["f1"], 4),
                "cv_auc_mean" : round(v["cv_auc_mean"], 4),
            }
            for k, v in resultados.items()
        }
    }

    print("\nAgente 2 completado. Metricas listas para el Agente 3.")

    return {
        "mejor_modelo" : mejor["modelo"],
        "nombre_mejor" : nombre_mejor,
        "y_test"       : y_test,
        "y_pred_mejor" : mejor["y_pred"],
        "y_prob_mejor" : mejor["y_prob"],
        "metricas"     : resultados,
        "reporte"      : reporte
    }


resultado_agente2 = agente_entrenador(resultado_agente1, random_state=42)

# ============================================================
# BLOQUE 5 — AGENTE 3: CARGA DEL MODELO (Qwen2.5-1.5B-Instruct)
# ============================================================
# Cargar el modelo de lenguaje en memoria. Este bloque se ejecuta
# una sola vez por sesion. El Bloque 6 reutiliza el modelo ya
# cargado sin necesidad de repetir este paso.
#
# Se utiliza Qwen2.5-1.5B-Instruct, un modelo decoder-only con
# instruction-tuning y chat_template formal (roles system/user/
# assistant). A diferencia de Flan-T5 (encoder-decoder para tareas
# cortas), Qwen2.5 esta disenado para razonamiento conversacional
# sobre contextos extensos, lo que mejora la coherencia de las
# respuestas.
#
# Librerias utilizadas:
#   AutoTokenizer         — carga el tokenizador correcto segun el modelo
#   AutoModelForCausalLM  — carga un modelo de lenguaje causal (decoder-only)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# Detectar si hay GPU disponible
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"[PASO 1] Dispositivo: {device.upper()}")
if device == "cpu":
    print("         Sin GPU: la carga puede tardar varios minutos.")

MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"

print(f"\n[PASO 2] Cargando modelo '{MODEL_NAME}'...")
print(f"         (Puede tardar varios minutos la primera vez)")

# Cargar vocabulario y reglas de tokenizacion de Qwen2.5
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# torch_dtype="auto" usa float16 con GPU y float32 con CPU
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype="auto",
    device_map=device
)

# Modo evaluacion: desactiva dropout para inferencia determinista
model.eval()

print(f"         Modelo cargado correctamente en {device.upper()}.")
print(f"\n[LISTO] Ejecutar el Bloque 6 para generar reportes o hacer preguntas.")

# ============================================================
# BLOQUE 6 — AGENTE 3: REPORTE Y PREGUNTAS (Qwen2.5-1.5B-Instruct)
# ============================================================
# Reutilizar el modelo cargado en el Bloque 5 para:
#   1. Calcular estadisticas adicionales del dataset original
#   2. Construir el contexto del analisis
#   3. Responder preguntas del usuario en lenguaje natural
#
# Se usa chat_template con roles system/user/assistant, el formato
# que Qwen2.5 espera para seguir instrucciones correctamente.

import pandas as pd


def calcular_estadisticas_extra(df: pd.DataFrame) -> dict:
    """
    Calcular estadisticas descriptivas adicionales sobre el dataset
    original que no estan en los reportes de los Agentes 1 y 2.

    Estas estadisticas (porcentaje de mujeres, supervivencia por
    sexo y clase, etc.) son necesarias para responder preguntas
    demograficas con datos reales en lugar de estimaciones.
    """
    pct_mujeres = (df["Sex"] == "female").mean() * 100
    pct_hombres = (df["Sex"] == "male").mean() * 100

    surv_por_sexo  = df.groupby("Sex")["Survived"].mean() * 100
    surv_por_clase = df.groupby("Pclass")["Survived"].mean() * 100

    pct_clase1 = (df["Pclass"] == 1).mean() * 100
    pct_clase2 = (df["Pclass"] == 2).mean() * 100
    pct_clase3 = (df["Pclass"] == 3).mean() * 100

    edad_promedio           = df["Age"].dropna().mean()
    edad_sobrevivientes     = df[df["Survived"] == 1]["Age"].dropna().mean()
    edad_no_sobrevivientes  = df[df["Survived"] == 0]["Age"].dropna().mean()

    fare_promedio = df["Fare"].mean()

    return {
        "total_pasajeros"        : len(df),
        "pct_mujeres"            : round(pct_mujeres, 1),
        "pct_hombres"            : round(pct_hombres, 1),
        "surv_mujeres"           : round(surv_por_sexo.get("female", 0), 1),
        "surv_hombres"           : round(surv_por_sexo.get("male", 0), 1),
        "surv_clase1"            : round(surv_por_clase.get(1, 0), 1),
        "surv_clase2"            : round(surv_por_clase.get(2, 0), 1),
        "surv_clase3"            : round(surv_por_clase.get(3, 0), 1),
        "pct_clase1"             : round(pct_clase1, 1),
        "pct_clase2"             : round(pct_clase2, 1),
        "pct_clase3"             : round(pct_clase3, 1),
        "edad_promedio"          : round(edad_promedio, 1),
        "edad_sobrevivientes"    : round(edad_sobrevivientes, 1),
        "edad_no_sobrevivientes" : round(edad_no_sobrevivientes, 1),
        "fare_promedio"          : round(fare_promedio, 2),
    }


def construir_contexto(reporte_a1: dict, reporte_a2: dict, stats_extra: dict) -> str:
    """
    Construir el texto de contexto con los resultados del pipeline.

    Este texto se incluye en el system prompt del modelo para que
    tenga acceso a todos los datos factuales necesarios al responder.
    """
    cols_num  = reporte_a1["cols_numericas"]
    cols_cat  = reporte_a1["cols_categoricas"]
    cols_desc = reporte_a1["cols_descartadas"]
    nulos_num = reporte_a1["nulos_num_antes"]
    nulos_cat = reporte_a1["nulos_cat_antes"]
    n_feat    = reporte_a1["columnas_output"]
    tasa_surv = reporte_a1["tasa_supervivencia"]

    mejor     = reporte_a2["mejor_modelo_nombre"]
    auc       = reporte_a2["auc"]
    accuracy  = reporte_a2["accuracy"]
    f1        = reporte_a2["f1"]
    precision = reporte_a2["precision"]
    recall    = reporte_a2["recall"]
    cv_auc    = reporte_a2["cv_auc_mean"]
    cv_std    = reporte_a2["cv_auc_std"]
    n_train   = reporte_a2["n_train"]
    n_test    = reporte_a2["n_test"]
    confusion = reporte_a2["confusion"]
    todos     = reporte_a2["todos_resultados"]

    comparativa = ""
    for nombre, metricas in todos.items():
        comparativa += (
            f"- {nombre}: AUC={metricas['auc']}, accuracy={metricas['accuracy']}, "
            f"F1={metricas['f1']}, cross-validation AUC={metricas['cv_auc_mean']}\n"
        )

    contexto = (
        f"DATASET: Titanic passenger survival prediction.\n"
        f"- Total passengers: {stats_extra['total_pasajeros']}\n"
        f"- Overall survival rate: {tasa_surv}%\n"
        f"- Female passengers: {stats_extra['pct_mujeres']}% | Male passengers: {stats_extra['pct_hombres']}%\n"
        f"- Survival rate for females: {stats_extra['surv_mujeres']}%\n"
        f"- Survival rate for males: {stats_extra['surv_hombres']}%\n"
        f"- Class distribution: 1st class {stats_extra['pct_clase1']}%, "
        f"2nd class {stats_extra['pct_clase2']}%, 3rd class {stats_extra['pct_clase3']}%\n"
        f"- Survival rate by class: 1st={stats_extra['surv_clase1']}%, "
        f"2nd={stats_extra['surv_clase2']}%, 3rd={stats_extra['surv_clase3']}%\n"
        f"- Average passenger age: {stats_extra['edad_promedio']} years\n"
        f"- Average age of survivors: {stats_extra['edad_sobrevivientes']} years\n"
        f"- Average age of non-survivors: {stats_extra['edad_no_sobrevivientes']} years\n"
        f"- Average ticket fare: ${stats_extra['fare_promedio']}\n\n"

        f"PREPROCESSING (Agent 1 - Normalizer):\n"
        f"- Training samples: {n_train} | Test samples: {n_test}\n"
        f"- Columns discarded (no predictive value): {', '.join(cols_desc)}\n"
        f"- Cabin was discarded because it had 77% missing values\n"
        f"- Numeric features used: {', '.join(cols_num)}\n"
        f"- Categorical features used: {', '.join(cols_cat)}\n"
        f"- Missing values in Age: {nulos_num}, imputed with median (robust to outliers)\n"
        f"- Missing values in Embarked: {nulos_cat}, imputed with most frequent value\n"
        f"- After imputation: zero missing values\n"
        f"- Numeric features scaled with StandardScaler (mean=0, std=1)\n"
        f"- Categorical features encoded with One-Hot Encoding\n"
        f"- Total features after preprocessing: {n_feat}\n\n"

        f"MODEL TRAINING (Agent 2 - Trainer):\n"
        f"- 5-fold cross-validation was used\n"
        f"- Selection criterion: AUC (robust to class imbalance: 62% did not survive vs 38% survived)\n"
        f"Results per model:\n"
        f"{comparativa}"
        f"- Best model: {mejor}\n"
        f"- Best model test AUC: {auc} (>0.8 = good discriminative ability)\n"
        f"- Best model accuracy: {accuracy} ({accuracy*100:.1f}% correct predictions)\n"
        f"- Best model F1 score: {f1}\n"
        f"- Best model precision: {precision} | recall: {recall}\n"
        f"- Cross-validation AUC: {cv_auc} +/- {cv_std}\n"
        f"- Confusion matrix: TN={confusion['tn']}, FP={confusion['fp']}, "
        f"FN={confusion['fn']}, TP={confusion['tp']}\n\n"

        f"INTERPRETATION:\n"
        f"- {mejor} was selected because survival relates approximately linearly "
        f"to Sex and Pclass, the two strongest predictors\n"
        f"- Logistic Regression models linear relationships directly, while "
        f"tree-based models are better for complex non-linear patterns\n"
        f"- An AUC of {auc} means: given a random survivor and a random "
        f"non-survivor, the model ranks the survivor correctly "
        f"{auc*100:.1f}% of the time"
    )

    return contexto


def generar_respuesta_chat(model, tokenizer, device: str,
                            contexto: str, pregunta_usuario: str,
                            max_new_tokens: int = 300) -> str:
    """
    Generar una respuesta usando el formato de chat de Qwen2.5.

    Construye mensajes con roles system/user y aplica el chat_template
    del tokenizador para obtener el formato exacto que el modelo espera.
    Se tokeniza el prompt resultante por separado para obtener un tensor
    limpio compatible con model.generate().

    Parametros:
      model            — modelo AutoModelForCausalLM cargado
      tokenizer        — AutoTokenizer correspondiente
      device           — cuda o cpu
      contexto         — texto con los datos del analisis
      pregunta_usuario — pregunta del usuario
      max_new_tokens   — maximo de tokens a generar
    """
    mensajes = [
        {
            "role": "system",
            "content": (
                "You are a data science assistant. You have access to the results "
                "of a machine learning pipeline analyzing the Titanic dataset. "
                "Answer questions using ONLY the information provided below. "
                "Be clear, specific, and explain your reasoning. "
                "If asked for a number, state it explicitly. "
                "If the information needed is not provided, say so honestly "
                "instead of making up numbers.\n\n"
                f"{contexto}"
            )
        },
        {
            "role": "user",
            "content": pregunta_usuario
        }
    ]

    # apply_chat_template con tokenize=False devuelve el texto con el
    # formato correcto de Qwen2.5 (<|im_start|>system, etc.)
    # Se tokeniza luego por separado para obtener un tensor input_ids limpio
    prompt_texto = tokenizer.apply_chat_template(
        mensajes,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs    = tokenizer(prompt_texto, return_tensors="pt").to(device)
    input_ids = inputs["input_ids"]

    # torch.no_grad() desactiva el calculo de gradientes en inferencia
    with torch.no_grad():
        output_ids = model.generate(
            input_ids,
            max_new_tokens=max_new_tokens,
            do_sample=True,       # muestreo probabilistico para respuestas mas naturales
            temperature=0.4,      # valores bajos dan respuestas mas centradas en los hechos
            top_p=0.9,            # nucleus sampling: descarta opciones muy improbables
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id
        )

    # Descartar los tokens del prompt y decodificar solo la respuesta generada
    respuesta_ids = output_ids[0][input_ids.shape[-1]:]
    respuesta     = tokenizer.decode(respuesta_ids, skip_special_tokens=True)

    return respuesta.strip()


# Preparar contexto del analisis
print("=" * 60)
print("AGENTE 3 — PREPARANDO CONTEXTO DEL ANALISIS")
print("=" * 60)

stats_extra       = calcular_estadisticas_extra(df_raw)
contexto_analisis = construir_contexto(
    resultado_agente1["reporte"],
    resultado_agente2["reporte"],
    stats_extra
)

print(f"\nContexto preparado ({len(contexto_analisis)} caracteres).")
print(f"Modelo en uso: Qwen2.5-1.5B-Instruct sobre {device.upper()}")

# Loop interactivo de preguntas
print(f"\n{'=' * 60}")
print(f"AGENTE 3 — ASISTENTE CONVERSACIONAL")
print(f"{'=' * 60}")
print(f"Comandos especiales:")
print(f"   'reporte' — genera un reporte general del analisis")
print(f"   'salir'   — termina la sesion")
print(f"\nEjemplos de preguntas:")
ejemplos = [
    "What percentage of passengers were female?",
    "Why was Logistic Regression selected as the best model?",
    "How does survival rate differ between men and women?",
    "Explain what the AUC score means in this context",
    "What does the confusion matrix tell us about errors?",
    "How were missing values handled and why?",
    "Was being in first class an advantage? Explain why.",
    "Is this model reliable enough to use? Why or why not?",
]
for i, e in enumerate(ejemplos, 1):
    print(f"   {i}. {e}")

print(f"\n{'=' * 60}\n")

while True:
    entrada = input("Pregunta (o 'reporte' / 'salir'): ").strip()

    if entrada.lower() in ["salir", "exit", "quit", "q"]:
        print("\nAgente 3 finalizado.")
        break

    if not entrada:
        print("   Por favor escribir una pregunta.\n")
        continue

    if entrada.lower() == "reporte":
        pregunta_efectiva = (
            "Write a clear, professional summary report covering: "
            "(1) the dataset and key demographics, (2) the preprocessing "
            "steps applied and why, (3) the models trained and their "
            "results, and (4) the final conclusion about model quality. "
            "Structure it in short paragraphs."
        )
        max_tokens = 400
    else:
        pregunta_efectiva = entrada
        max_tokens        = 250

    print(f"   Generando respuesta...")

    respuesta = generar_respuesta_chat(
        model, tokenizer, device,
        contexto_analisis, pregunta_efectiva,
        max_new_tokens=max_tokens
    )

    print(f"\n{respuesta}\n")
